import type { ChatMessage } from '../../../shared/chatMessages'
import type { GradeResult } from '../../../shared/gradeResult'
import { humanizeNodeId } from '../../../shared/humanizeId'
import { renderMathHtml } from '../components/MathRenderer'
import { splitAroundTicket } from './ticketParser'
import printCss from '../../print.css?raw'
import katexCss from 'katex/dist/katex.min.css?raw'

/** Minimal shape the export path needs from SessionHistoryDrawer's `GradeBatch` —
 * kept as a structural (not imported) type so this module doesn't reach into a
 * component file for a type it only needs two fields of. */
export interface SittingGradeBatch {
  atIndex: number
  results: GradeResult[]
}

export interface SittingMeta {
  /** The topic's title (Learn), or "Review" for the review queue — Review has
   * no per-topic title since a sitting there can span many nodes. */
  title: string
  /** The sitting's own `startedAt` (ISO) — rendered as a local date/time. */
  startedAt: string
}

function formatSittingDate(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return iso
  return (
    d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }) +
    ' · ' +
    d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })
  )
}

function stabilityCell(days: number | null): string {
  return days !== null ? `${days.toFixed(1)}d` : '—'
}

function nextReviewCell(intervalDays: number | null): string {
  if (intervalDays === null) return '—'
  if (intervalDays <= 0) return 'due now'
  return intervalDays === 1 ? '1 day' : `${Math.round(intervalDays)} days`
}

function gradesAt(grades: SittingGradeBatch[], idx: number): GradeResult[] {
  return grades.filter((g) => g.atIndex === idx).flatMap((g) => g.results)
}

// ---------------------------------------------------------------------------
// Markdown
// ---------------------------------------------------------------------------

function receiptsMarkdown(results: GradeResult[]): string[] {
  if (results.length === 0) return []
  const rows = results.map(
    (r) =>
      `| ${humanizeNodeId(r.node)} | ${r.grade} | ${stabilityCell(r.sBefore)} → ${stabilityCell(r.sAfter)} | ${nextReviewCell(r.intervalDays)} |`,
  )
  return ['**Receipts**', '', '| Node | Grade | Stability | Next review |', '| --- | --- | --- | --- |', ...rows, '']
}

/** Assembles the sitting's transcript into clean, readable-raw Markdown — a
 * lab-notebook page. Reuses exactly the shaping the history drawer already did
 * (`messages`/`grades` come straight from its `buildHistoryTimeline`, or the
 * same shape freshly rebuilt from `getTranscript` for the currently-open
 * sitting — see LearnSessionView/ReviewSessionView's export handlers) rather
 * than re-deriving anything from the raw transcript here. Math is left as
 * literal `$...$`/`$$...$$` (valid, readable in any plain editor); the
 * dialogue skill's own `**LABEL**:` convention is already valid Markdown bold
 * and needs no rewriting either. */
export function sittingToMarkdown(messages: ChatMessage[], grades: SittingGradeBatch[], meta: SittingMeta): string {
  const lines: string[] = [`# ${meta.title}`, '', `*Sitting of ${formatSittingDate(meta.startedAt)}*`, '', '---', '']

  lines.push(...receiptsMarkdown(gradesAt(grades, 0)))

  messages.forEach((m, i) => {
    lines.push(m.role === 'user' ? '### You' : '### Tutor')
    lines.push('')
    lines.push(m.role === 'user' ? m.text.split('\n').map((l) => `> ${l}`).join('\n') : m.text)
    lines.push('')
    lines.push(...receiptsMarkdown(gradesAt(grades, i + 1)))
  })

  lines.push('---', '', '*Generated by Engram Desktop · learning engine: engram (nagisanzenin)*')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Print HTML (PDF path)
// ---------------------------------------------------------------------------

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function receiptsHtml(results: GradeResult[]): string {
  if (results.length === 0) return ''
  const rows = results
    .map(
      (r) =>
        `<tr><td>${escapeHtml(humanizeNodeId(r.node))}</td><td>${r.grade}</td><td>${stabilityCell(r.sBefore)} → ${stabilityCell(r.sAfter)}</td><td>${nextReviewCell(r.intervalDays)}</td></tr>`,
    )
    .join('')
  return `<div class="sitting-receipts"><div class="sitting-receipts-caption">Receipts</div><table><thead><tr><th>Node</th><th>Grade</th><th>Stability</th><th>Next review</th></tr></thead><tbody>${rows}</tbody></table></div>`
}

/** Renders one chunk of prose — math via the real KaTeX pipeline
 * (`renderMathHtml`, the same tokenizer `MathRenderer` uses live), with any
 * session-ticket fence pulled out into its own small field table instead of
 * a raw code block. Recurses around the ticket exactly like
 * `PlainDialogueBlock` does, so a message with prose before/after the ticket
 * still reads in order. */
function proseHtml(text: string): string {
  const split = splitAroundTicket(text)
  if (!split) return `<div class="sitting-body">${renderMathHtml(text)}</div>`
  const rows = split.ticket.fields
    .map((f) => `<tr><td>${escapeHtml(f.key)}</td><td>${escapeHtml(f.value)}</td></tr>`)
    .join('')
  const ticketHtml = `<div class="sitting-ticket"><div class="ticket-header">engram · ${escapeHtml(split.ticket.kind)} · ${escapeHtml(split.ticket.mode)}</div><table>${rows}</table></div>`
  return [
    split.before && `<div class="sitting-body">${renderMathHtml(split.before)}</div>`,
    ticketHtml,
    split.after && `<div class="sitting-body">${renderMathHtml(split.after)}</div>`,
  ]
    .filter(Boolean)
    .join('')
}

/** Builds a SELF-CONTAINED print HTML document — every style inlined (this
 * page's own print.css plus KaTeX's stylesheet), no external requests, so
 * loading it in main's hidden `BrowserWindow` (see main/session/exportSitting.ts)
 * never touches the network or the app's own runtime stylesheet.
 *
 * Math arrives genuinely KaTeX-rendered (via `renderMathHtml`, re-running the
 * same synchronous `katex.renderToString` call `MathRenderer` makes live) —
 * this was chosen over two other options considered: (a) leaving math as
 * literal `$...$` in the PDF too, which would read badly for the math-heavy
 * physics topics this app actually gets used for, and (b) grabbing the live
 * drawer's already-rendered `element.innerHTML` wholesale, which would carry
 * along Tailwind utility classes and `var(--color-*)` references that mean
 * nothing without the app's compiled runtime stylesheet (itself dark-themed,
 * not this print page's cream-paper look) — and would drag in stateful
 * components (GradeResultCard's flip/count-up animation) that have no single
 * "final" DOM snapshot to grab. Re-deriving the KaTeX HTML directly is cheap
 * (pure, synchronous) and keeps this document's styling fully independent of
 * the app shell. KaTeX's own webfont files aren't reachable from this
 * standalone document, so its CSS falls back to system serif/mono — see
 * print.css's file header. */
export function sittingToPrintHtml(messages: ChatMessage[], grades: SittingGradeBatch[], meta: SittingMeta): string {
  const body: string[] = []
  body.push(...[receiptsHtml(gradesAt(grades, 0))].filter(Boolean))

  messages.forEach((m, i) => {
    const label = m.role === 'user' ? 'You' : 'Tutor'
    body.push(
      `<div class="sitting-turn ${m.role}"><div class="sitting-turn-label">${label}</div>${
        m.role === 'user' ? `<div class="sitting-body">${renderMathHtml(m.text)}</div>` : proseHtml(m.text)
      }</div>`,
    )
    const receipts = receiptsHtml(gradesAt(grades, i + 1))
    if (receipts) body.push(receipts)
  })

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(meta.title)}</title>
<style>${katexCss}</style>
<style>${printCss}</style>
</head>
<body>
<div class="sitting-header">
<h1>${escapeHtml(meta.title)}</h1>
<div class="sitting-meta">Sitting of ${escapeHtml(formatSittingDate(meta.startedAt))}</div>
</div>
${body.join('\n')}
<div class="sitting-footer">Generated by Engram Desktop · learning engine: engram (nagisanzenin)</div>
</body>
</html>`
}
